INSERT INTO app_city(name) VALUES ("Acari");
INSERT INTO app_city(name) VALUES ("Afonso Bezerra");
INSERT INTO app_city(name) VALUES ("Agua Nova");
INSERT INTO app_city(name) VALUES ("Alexandria");
INSERT INTO app_city(name) VALUES ("Almino Afonso");
INSERT INTO app_city(name) VALUES ("Alto do Rodrigues");
INSERT INTO app_city(name) VALUES ("Angicos");
INSERT INTO app_city(name) VALUES ("Antônio Martins");
INSERT INTO app_city(name) VALUES ("Apodi");
INSERT INTO app_city(name) VALUES ("Areia Branca");
INSERT INTO app_city(name) VALUES ("Arês");
INSERT INTO app_city(name) VALUES ("Açu");
INSERT INTO app_city(name) VALUES ("Baraúna");
INSERT INTO app_city(name) VALUES ("Barcelona");
INSERT INTO app_city(name) VALUES ("Baía Formosa");
INSERT INTO app_city(name) VALUES ("Bento Fernandes");
INSERT INTO app_city(name) VALUES ("Bodó");
INSERT INTO app_city(name) VALUES ("Bom Jesus");
INSERT INTO app_city(name) VALUES ("Brejinho");
INSERT INTO app_city(name) VALUES ("Caicó");
INSERT INTO app_city(name) VALUES ("Caiçara do Norte");
INSERT INTO app_city(name) VALUES ("Caiçara do Rio do Vento");
INSERT INTO app_city(name) VALUES ("Campo Grande");
INSERT INTO app_city(name) VALUES ("Campo Redondo");
INSERT INTO app_city(name) VALUES ("Canguaretama");
INSERT INTO app_city(name) VALUES ("Caraúbas");
INSERT INTO app_city(name) VALUES ("Carnaubais");
INSERT INTO app_city(name) VALUES ("Carnaúba dos Dantas");
INSERT INTO app_city(name) VALUES ("Ceará-Mirim");
INSERT INTO app_city(name) VALUES ("Cerro Corá");
INSERT INTO app_city(name) VALUES ("Coronel Ezequiel");
INSERT INTO app_city(name) VALUES ("Coronel João Pessoa");
INSERT INTO app_city(name) VALUES ("Cruzeta");
INSERT INTO app_city(name) VALUES ("Currais Novos");
INSERT INTO app_city(name) VALUES ("Doutor Severiano");
INSERT INTO app_city(name) VALUES ("Encanto");
INSERT INTO app_city(name) VALUES ("Equador");
INSERT INTO app_city(name) VALUES ("Espírito Santo");
INSERT INTO app_city(name) VALUES ("Extremoz");
INSERT INTO app_city(name) VALUES ("Felipe Guerra");
INSERT INTO app_city(name) VALUES ("Fernando Pedroza");
INSERT INTO app_city(name) VALUES ("Florânia");
INSERT INTO app_city(name) VALUES ("Francisco Dantas");
INSERT INTO app_city(name) VALUES ("Frutuoso Gomes");
INSERT INTO app_city(name) VALUES ("Galinhos");
INSERT INTO app_city(name) VALUES ("Goianinha");
INSERT INTO app_city(name) VALUES ("Governador Dix-Sept Rosado");
INSERT INTO app_city(name) VALUES ("Grossos");
INSERT INTO app_city(name) VALUES ("Guamaré");
INSERT INTO app_city(name) VALUES ("Ielmo Marinho");
INSERT INTO app_city(name) VALUES ("Ipanguaçu");
INSERT INTO app_city(name) VALUES ("Ipueira");
INSERT INTO app_city(name) VALUES ("Itajá");
INSERT INTO app_city(name) VALUES ("Itaú");
INSERT INTO app_city(name) VALUES ("Jandaíra");
INSERT INTO app_city(name) VALUES ("Janduís");
INSERT INTO app_city(name) VALUES ("Januário Cicco");
INSERT INTO app_city(name) VALUES ("Japi");
INSERT INTO app_city(name) VALUES ("Jardim de Angicos");
INSERT INTO app_city(name) VALUES ("Jardim de Piranhas");
INSERT INTO app_city(name) VALUES ("Jardim do Seridó");
INSERT INTO app_city(name) VALUES ("Jaçanã");
INSERT INTO app_city(name) VALUES ("José da Penha");
INSERT INTO app_city(name) VALUES ("João Câmara");
INSERT INTO app_city(name) VALUES ("João Dias");
INSERT INTO app_city(name) VALUES ("Jucurutu");
INSERT INTO app_city(name) VALUES ("Jundiá");
INSERT INTO app_city(name) VALUES ("Lagoa Nova");
INSERT INTO app_city(name) VALUES ("Lagoa Salgada");
INSERT INTO app_city(name) VALUES ("Lagoa d'Anta");
INSERT INTO app_city(name) VALUES ("Lagoa de Pedras");
INSERT INTO app_city(name) VALUES ("Lagoa de Velhos");
INSERT INTO app_city(name) VALUES ("Lajes");
INSERT INTO app_city(name) VALUES ("Lajes Pintadas");
INSERT INTO app_city(name) VALUES ("Lucrécia");
INSERT INTO app_city(name) VALUES ("Luís Gomes");
INSERT INTO app_city(name) VALUES ("Macau");
INSERT INTO app_city(name) VALUES ("Macaíba");
INSERT INTO app_city(name) VALUES ("Major Sales");
INSERT INTO app_city(name) VALUES ("Marcelino Vieira");
INSERT INTO app_city(name) VALUES ("Martins");
INSERT INTO app_city(name) VALUES ("Maxaranguape");
INSERT INTO app_city(name) VALUES ("Messias Targino");
INSERT INTO app_city(name) VALUES ("Montanhas");
INSERT INTO app_city(name) VALUES ("Monte Alegre");
INSERT INTO app_city(name) VALUES ("Monte das Gameleiras");
INSERT INTO app_city(name) VALUES ("Mossoró");
INSERT INTO app_city(name) VALUES ("Natal");
INSERT INTO app_city(name) VALUES ("Nova Cruz");
INSERT INTO app_city(name) VALUES ("Nísia Floresta");
INSERT INTO app_city(name) VALUES ("Olho d'Água do Borges");
INSERT INTO app_city(name) VALUES ("Ouro Branco");
INSERT INTO app_city(name) VALUES ("Paraná");
INSERT INTO app_city(name) VALUES ("Parazinho");
INSERT INTO app_city(name) VALUES ("Paraú");
INSERT INTO app_city(name) VALUES ("Parelhas");
INSERT INTO app_city(name) VALUES ("Parnamirim");
INSERT INTO app_city(name) VALUES ("Passa e Fica");
INSERT INTO app_city(name) VALUES ("Passagem");
INSERT INTO app_city(name) VALUES ("Patu");
INSERT INTO app_city(name) VALUES ("Pau dos Ferros");
INSERT INTO app_city(name) VALUES ("Pedra Grande");
INSERT INTO app_city(name) VALUES ("Pedra Preta");
INSERT INTO app_city(name) VALUES ("Pedro Avelino");
INSERT INTO app_city(name) VALUES ("Pedro Velho");
INSERT INTO app_city(name) VALUES ("Pendências");
INSERT INTO app_city(name) VALUES ("Pilões");
INSERT INTO app_city(name) VALUES ("Portalegre");
INSERT INTO app_city(name) VALUES ("Porto do Mangue");
INSERT INTO app_city(name) VALUES ("Poço Branco");
INSERT INTO app_city(name) VALUES ("Pureza");
INSERT INTO app_city(name) VALUES ("Rafael Fernandes");
INSERT INTO app_city(name) VALUES ("Rafael Godeiro");
INSERT INTO app_city(name) VALUES ("Riacho da Cruz");
INSERT INTO app_city(name) VALUES ("Riacho de Santana");
INSERT INTO app_city(name) VALUES ("Riachuelo");
INSERT INTO app_city(name) VALUES ("Rio do Fogo");
INSERT INTO app_city(name) VALUES ("Rodolfo Fernandes");
INSERT INTO app_city(name) VALUES ("Ruy Barbosa");
INSERT INTO app_city(name) VALUES ("Santa Cruz");
INSERT INTO app_city(name) VALUES ("Santa Maria");
INSERT INTO app_city(name) VALUES ("Santana do Matos");
INSERT INTO app_city(name) VALUES ("Santana do Seridó");
INSERT INTO app_city(name) VALUES ("Santo Antônio");
INSERT INTO app_city(name) VALUES ("Senador Elói de Souza");
INSERT INTO app_city(name) VALUES ("Senador Georgino Avelino");
INSERT INTO app_city(name) VALUES ("Serra Caiada");
INSERT INTO app_city(name) VALUES ("Serra Negra do Norte");
INSERT INTO app_city(name) VALUES ("Serra de São Bento");
INSERT INTO app_city(name) VALUES ("Serra do Mel");
INSERT INTO app_city(name) VALUES ("Serrinha");
INSERT INTO app_city(name) VALUES ("Serrinha dos Pintos");
INSERT INTO app_city(name) VALUES ("Severiano Melo");
INSERT INTO app_city(name) VALUES ("São Bento do Norte");
INSERT INTO app_city(name) VALUES ("São Bento do Trairí");
INSERT INTO app_city(name) VALUES ("São Fernando");
INSERT INTO app_city(name) VALUES ("São Francisco do Oeste");
INSERT INTO app_city(name) VALUES ("São Gonçalo do Amarante");
INSERT INTO app_city(name) VALUES ("São José de Mipibu");
INSERT INTO app_city(name) VALUES ("São José do Campestre");
INSERT INTO app_city(name) VALUES ("São José do Seridó");
INSERT INTO app_city(name) VALUES ("São João do Sabugi");
INSERT INTO app_city(name) VALUES ("São Miguel");
INSERT INTO app_city(name) VALUES ("São Miguel do Gostoso");
INSERT INTO app_city(name) VALUES ("São Paulo do Potengi");
INSERT INTO app_city(name) VALUES ("São Pedro");
INSERT INTO app_city(name) VALUES ("São Rafael");
INSERT INTO app_city(name) VALUES ("São Tomé");
INSERT INTO app_city(name) VALUES ("São Vicente");
INSERT INTO app_city(name) VALUES ("Sítio Novo");
INSERT INTO app_city(name) VALUES ("Taboleiro Grande");
INSERT INTO app_city(name) VALUES ("Taipu");
INSERT INTO app_city(name) VALUES ("Tangará");
INSERT INTO app_city(name) VALUES ("Tenente Ananias");
INSERT INTO app_city(name) VALUES ("Tenente Laurentino Cruz");
INSERT INTO app_city(name) VALUES ("Tibau");
INSERT INTO app_city(name) VALUES ("Tibau do Sul");
INSERT INTO app_city(name) VALUES ("Timbaúba dos Batistas");
INSERT INTO app_city(name) VALUES ("Touros");
INSERT INTO app_city(name) VALUES ("Triunfo Potiguar");
INSERT INTO app_city(name) VALUES ("Umarizal");
INSERT INTO app_city(name) VALUES ("Upanema");
INSERT INTO app_city(name) VALUES ("Venha-Ver");
INSERT INTO app_city(name) VALUES ("Vera Cruz");
INSERT INTO app_city(name) VALUES ("Vila Flor");
INSERT INTO app_city(name) VALUES ("Viçosa");
INSERT INTO app_city(name) VALUES ("Várzea");
